# Generated by Django 4.1.3 on 2023-05-04 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Learning',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_learning', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_learning', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning',
                'verbose_name_plural': 'Learnings',
            },
        ),
    ]
