# Generated by Django 4.1.3 on 2023-05-04 20:21

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='O nome da pessoas que mandando o mensagem', max_length=150)),
                ('referente', models.DateTimeField(default=django.utils.timezone.now, help_text='A data de referência')),
                ('dias', models.IntegerField(blank=True, default=0, help_text='quantidade de dia que estão em atraso', null=True)),
                ('email', models.EmailField(help_text='O email de resposta', max_length=254, verbose_name='E-mail')),
                ('message', models.TextField(blank=True, help_text='Conteudo da mensagem')),
                ('resposta', models.BooleanField(default=False, help_text='Se a messagem ja teve resposta')),
            ],
            options={
                'verbose_name': 'messagem',
                'verbose_name_plural': 'messagens',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='O nome da pessoas que mandando o mensagem', max_length=150, null=True)),
                ('referente', models.DateTimeField(default=django.utils.timezone.now, help_text='A data de referência')),
                ('email', models.EmailField(help_text='O email de resposta', max_length=254, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
            },
        ),
    ]
