# Generated by Django 4.1.3 on 2023-05-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_analytics_owner'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='students',
        ),
        migrations.RemoveField(
            model_name='user',
            name='teachers',
        ),
        migrations.AddField(
            model_name='user',
            name='students',
            field=models.ManyToManyField(related_name='student_course', to='courses.course'),
        ),
        migrations.AddField(
            model_name='user',
            name='teachers',
            field=models.ManyToManyField(related_name='teachers_course', to='courses.course'),
        ),
    ]
