# Generated by Django 4.1.3 on 2023-05-05 18:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_analytics_owner'),
        ('accounts', '0002_remove_user_students_remove_user_teachers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='expert',
            field=models.ManyToManyField(related_name='expert_course', to='courses.subcategorie'),
        ),
    ]
