# Generated by Django 4.1.3 on 2023-05-05 18:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_description_user_expert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
