# Generated by Django 4.1.3 on 2023-05-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_analytics_owner'),
        ('accounts', '0004_alter_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='student_course', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='user',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='teachers_course', to='courses.course'),
        ),
    ]
