# Generated by Django 4.1.3 on 2023-05-11 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_analytics_owner'),
        ('blog', '0002_rename_body_post_overview_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blog_ctegorie', to='courses.categorie'),
            preserve_default=False,
        ),
    ]
