# Generated by Django 4.1.3 on 2023-05-04 20:21

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='user')),
                ('slug', models.SlugField(null=True)),
                ('expert', models.CharField(help_text='A habilidade do instrutor', max_length=190, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('rating', models.FloatField(default=0, help_text='Avaliação do instrutor')),
                ('reviews', models.IntegerField(default=0, help_text='Comentários dos alunos')),
                ('is_active', models.BooleanField(default=False)),
                ('courses', models.ManyToManyField(blank=True, related_name='course_author', to='courses.course')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_course', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(blank=True, related_name='students_enrolled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titulo da avaliação', max_length=290)),
                ('message', models.TextField(help_text='O conteúdo da messagem')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rate', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_instrutor_review', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
