# Generated by Django 4.0.5 on 2022-11-18 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('overview', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('publish', models.DateTimeField(blank=True)),
                ('status', models.CharField(choices=[('projeto', 'projeto'), ('analizando', 'analizando'), ('aprovado', 'aprovado'), ('cancelado', 'cancelado')], default='projeto', max_length=14)),
                ('popularity', models.IntegerField(default=0, help_text='O popularidade')),
                ('poster', models.URLField(blank=True)),
                ('poster_url', models.URLField(blank=True)),
                ('linguagem', models.CharField(blank=True, max_length=150)),
                ('average_Rating', models.CharField(blank=True, max_length=3)),
                ('average_Count', models.CharField(blank=True, max_length=3)),
                ('votes_Count', models.IntegerField(default=0)),
                ('likes', models.IntegerField(blank=True, default=0, null=True)),
                ('total_horas', models.CharField(default='00:00:00', max_length=150)),
                ('views', models.IntegerField(default=0, help_text='O total de visualizações')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_created', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.subject')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
