# Generated by Django 4.1.3 on 2023-05-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_analytics_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='complete_per',
            field=models.IntegerField(blank=True, default=0, help_text='A quantidade lesson', null=True),
        ),
    ]
