# Generated by Django 4.1.3 on 2023-05-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_analytics_complete_per'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
